### ISSUE TITLE
Repository setup is incomplete.

### ISSUE THREAD

**Issue by mfernest** [smarrone/SEBC#7]
Please change the Issue labels according to the instructions in the README. This change speeds up the evaluation process for me.

Let me know once the changes are made and I'll review the lab work.

Regards,

Michael

**Comment by smarrone** [comment]
Hi Michael,
I have done what is writed in the callenge:
Label it started
Label the issue review

Silvia

**Comment by smarrone** [comment]
Hi Michael,
I have modified the lables
